name = "renderer"
description = "2D Software Renderer"
version = "0.1.0-dev"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["renderer", "draw", "2d"]

[[depends-on]]
vss_text = "^26.0.0"

[[depends-on]]
sparklib = "^15.1.0"
